[QoS] Import buffer_defs with context in qos_config.j2 (#24217)
<!--
 Please make sure you've read and understood our contributing guidelines:
 https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

 failure_prs.log Make sure all your commits include a signature generated with `git commit -s` **

 If this is a bug fix, make sure your description includes "fixes #xxxx", or
 "closes #xxxx" or "resolves #xxxx"

 Please provide the following information:
-->
Added with context to the Jinja2 import of `buffers.json.j2` in `qos_config.j2`
#### Why I did it
To ensure DEVICE_METADATA and other context variables are available when `buffers.json.j2` is imported into `qos_config.j2`. Without this, template rendering failed on a Cisco 8102 SKU due to missing context since jinja2 doesn't carry context over multiple calls.

```
admin@str2-8102-02:~$ sudo config load_minigraph --override_config -y
Acquired lock on /etc/sonic/reload.lock
Disabling container and routeCheck monitoring ...
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json --write-to-db
Running command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment
Running command: config qos reload --no-dynamic-buffer --no-delay
Traceback (most recent call last):
 File "/usr/local/bin/sonic-cfggen", line 530, in <module>
 main()
 File "/usr/local/bin/sonic-cfggen", line 494, in main
 template_data = template.render(data)
 ^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
 self.environment.handle_exception()
 File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
 raise rewrite_traceback_stack(source=source)
 File "/usr/share/sonic/device/x86_64-8102_64h_o-r0/Cisco-8102-C64/qos.json.j2", line 572, in top-level template code
 {%- include 'qos_config.j2' %}
 ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/share/sonic/templates/qos_config.j2", line 11, in top-level template code
 {% import "buffers.json.j2" as buffer_defs %}
^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1405, in make_module
 return TemplateModule(self, ctx)
 ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1535, in __init__
 body_stream = list(template.root_render_func(context)) # type: ignore
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/share/sonic/device/x86_64-8102_64h_o-r0/Cisco-8102-C64/buffers.json.j2", line 2, in top-level template code
 {%- include 'buffers_config.j2' %}
 ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/share/sonic/templates/buffers_config.j2", line 46, in top-level template code
 {%- import 'buffers_defaults_%s.j2' % filename_postfix as defs with context %}
^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1405, in make_module
 return TemplateModule(self, ctx)
 ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1535, in __init__
 body_stream = list(template.root_render_func(context)) # type: ignore
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/share/sonic/device/x86_64-8102_64h_o-r0/Cisco-8102-C64/buffers_defaults_t0.j2", line 1, in top-level template code
 {% set sms_64mb = ('platform' in DEVICE_METADATA['localhost'] and
 ^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 466, in getitem
 return obj[argument]
 ~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'DEVICE_METADATA' is undefined
Running command: /usr/local/bin/sonic-cfggen -d -t /usr/share/sonic/device/x86_64-8102_64h_o-r0/Cisco-8102-C64/buffers.json.j2,/tmp/cfg_buffer.json -t /usr/share/sonic/device/x86_64-8102_64h_o-r0/Cisco-8102-C64/qos.json.j2,/tmp/cfg_qos.json -y /etc/sonic/sonic_version.yml
Released lock on /etc/sonic/reload.lock
```

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Add context
#### How to verify it

```
admin@str2-8102-02:~$ sudo config load_minigraph --override_config -y
Acquired lock on /etc/sonic/reload.lock
Disabling container and routeCheck monitoring ...
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json --write-to-db
Running command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment
Running command: config qos reload --no-dynamic-buffer --no-delay
Running command: /usr/local/bin/sonic-cfggen -d -t /usr/share/sonic/device/x86_64-8102_64h_o-r0/Cisco-8102-C64/buffers.json.j2,/tmp/cfg_buffer.json -t /usr/share/sonic/device/x86_64-8102_64h_o-r0/Cisco-8102-C64/qos.json.j2,/tmp/cfg_qos.json -y /etc/sonic/sonic_version.yml
Running command: /usr/local/bin/sonic-cfggen -j /tmp/cfg_buffer.json -j /tmp/cfg_qos.json --write-to-db
Running command: pfcwd start_default
Running command: config override-config-table /etc/sonic/golden_config_db.json
Removing configDB overriden table first ...
Overriding input config to configDB ...
Overriding completed. No service is restarted.
Restarting SONiC target ...
Enabling container and routeCheck monitoring ...
Reloading Monit configuration ...
Reinitializing monit daemon
Please note setting loaded from minigraph will be lost after system reboot. To preserve setting, run `config save`.
Released lock on /etc/sonic/reload.lock

admin@str2-8102-02:~$ docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
becabc6d4717 docker-sonic-telemetry:latest "/usr/local/bin/supe…" 4 hours ago Up 8 minutes telemetry
13ac3a42cfeb docker-snmp:latest "/usr/bin/docker-snm…" 4 hours ago Up 8 minutes snmp
4a6518963249 docker-platform-monitor:latest "/usr/bin/docker_ini…" 4 hours ago Up 8 minutes pmon
f2b8580c64c7 docker-lldp:latest "/usr/bin/docker-lld…" 4 hours ago Up 8 minutes lldp
04132113666e docker-sonic-gnmi:latest "/usr/local/bin/supe…" 4 hours ago Up 8 minutes gnmi
6a29b5659021 docker-vnet-monitor:latest "/usr/local/bin/supe…" 4 hours ago Up 8 minutes vnet-monitor
4f9585c8c880 docker-sonic-bmp:latest "/usr/local/bin/supe…" 4 hours ago Up 8 minutes bmp
239bb70ea984 docker-eventd:latest "/usr/local/bin/supe…" 4 hours ago Up 8 minutes eventd
54c31cfbe8c1 docker-fpm-frr:latest "/usr/bin/docker_ini…" 4 hours ago Up 8 minutes bgp
4511d04bc63b docker-router-advertiser:latest "/usr/bin/docker-ini…" 4 hours ago Up 8 minutes radv
7721532f8d4c docker-syncd-cisco:latest "/usr/local/bin/supe…" 4 hours ago Up 8 minutes syncd
e1b89d3bd331 docker-teamd:latest "/usr/local/bin/supe…" 4 hours ago Up 8 minutes teamd
e7e01769b3bb docker-sysmgr:latest "/usr/local/bin/supe…" 4 hours ago Up 8 minutes sysmgr
3bc23a24a568 docker-orchagent:latest "/usr/bin/docker-ini…" 4 hours ago Up 8 minutes swss
d24ed97a8f56 docker-sonic-restapi:latest "/usr/local/bin/supe…" 4 hours ago Up 8 minutes restapi
9167ee385350 docker-acms:latest "/usr/local/bin/supe…" 4 hours ago Up 4 hours acms
abc7cd15cb83 docker-database:latest "/usr/local/bin/dock…" 4 hours ago Up 4 hours database
```

<!--
If PR needs to be backported, then the PR must be tested against the base branch and the earliest backport release branch and provide tested image version on these two branches. For example, if the PR is requested for master, 202211 and 202012, then the requester needs to provide test results on master and 202012.
-->

#### Which release branch to backport (provide reason below if selected)

<!--
- Note we only backport fixes to a release branch, *not* features!
- Please also provide a reason for the backporting below.
- e.g.
- [x] 202006
-->

- [ ] 202205
- [ ] 202211
- [ ] 202305
- [ ] 202311
- [ ] 202405
- [ ] 202411
- [X] 202505

#### Tested branch (Please provide the tested image version)

<!--
- Please provide tested image version
- e.g.
- [x] 20201231.100
-->

- [ ] <!-- image version 1 -->
- [ ] <!-- image version 2 -->

#### Description for the changelog
<!--
Write a short (one line) summary that describes the changes in this
pull request for inclusion in the changelog:
-->
Added with context to the Jinja2 import of buffers.json.j2 in qos_config.j2
<!--
 Ensure to add label/tag for the feature raised. example - PR#2174 under sonic-utilities repo. where, Generic Config and Update feature has been labelled as GCU.
-->

#### Link to config_db schema for YANG module changes
<!--
Provide a link to config_db schema for the table for which YANG model
is defined
Link should point to correct section on https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md
-->

#### A picture of a cute animal (not mandatory but encouraged)